unit MainForm;
interface
uses System.SysUtils, System.Classes, System.IOUtils, Vcl.Forms, Vcl.Controls, Vcl.StdCtrls, Vcl.Dialogs, Vcl.Grids, RenameEngine;
type TMainWindow=class(TForm) private FFolder,FPrefix,FSuffix,FFind,FReplace:TEdit; FNumber:TCheckBox; FGrid:TStringGrid; FItems:TArray<TRenameItem>; procedure Pick(Sender:TObject); procedure BuildPreview(Sender:TObject); procedure Apply(Sender:TObject); procedure Revert(Sender:TObject); function LogPath:string; public constructor Create(AOwner:TComponent); override; end;
var MainWindow:TMainWindow;
implementation
constructor TMainWindow.Create(AOwner:TComponent); var B:TButton; L:TLabel; X:Integer; procedure Field(const CaptionText:string; var E:TEdit; W:Integer); begin L:=TLabel.Create(Self); L.Parent:=Self; L.Caption:=CaptionText; L.SetBounds(X,60,W,18); E:=TEdit.Create(Self); E.Parent:=Self; E.SetBounds(X,80,W,25); Inc(X,W+10); end;
begin inherited; Caption:='Organizador de Arquivos'; Width:=1100; Height:=680; Position:=poScreenCenter; FFolder:=TEdit.Create(Self); FFolder.Parent:=Self; FFolder.SetBounds(10,15,800,27); B:=TButton.Create(Self); B.Parent:=Self; B.Caption:='Pasta...'; B.SetBounds(820,13,90,30); B.OnClick:=Pick; X:=10; Field('Prefixo',FPrefix,150); Field('Sufixo',FSuffix,150); Field('Localizar',FFind,180); Field('Substituir',FReplace,180); FNumber:=TCheckBox.Create(Self); FNumber.Parent:=Self; FNumber.Caption:='Numerar'; FNumber.SetBounds(X,82,90,22); B:=TButton.Create(Self); B.Parent:=Self; B.Caption:='Gerar prévia'; B.SetBounds(10,120,120,30); B.OnClick:=BuildPreview; B:=TButton.Create(Self); B.Parent:=Self; B.Caption:='Confirmar'; B.SetBounds(140,120,110,30); B.OnClick:=Apply; B:=TButton.Create(Self); B.Parent:=Self; B.Caption:='Desfazer'; B.SetBounds(260,120,100,30); B.OnClick:=Revert; FGrid:=TStringGrid.Create(Self); FGrid.Parent:=Self; FGrid.SetBounds(10,165,1060,465); FGrid.Anchors:=[akLeft,akTop,akRight,akBottom]; FGrid.ColCount:=3; FGrid.RowCount:=2; FGrid.FixedRows:=1; FGrid.Options:=FGrid.Options+[goColSizing]; FGrid.Cells[0,0]:='Original'; FGrid.Cells[1,0]:='Novo nome'; FGrid.Cells[2,0]:='Status'; FGrid.ColWidths[0]:=410; FGrid.ColWidths[1]:=410; FGrid.ColWidths[2]:=180; end;
procedure TMainWindow.Pick(Sender:TObject); var D:TFileOpenDialog; begin D:=TFileOpenDialog.Create(nil); try D.Options:=[fdoPickFolders]; if D.Execute then FFolder.Text:=D.FileName; finally D.Free; end; end;
function TMainWindow.LogPath:string; begin Result:=TPath.Combine(FFolder.Text,'.organizador-undo.tsv'); end;
procedure TMainWindow.BuildPreview(Sender:TObject); var I:Integer; begin if not TDirectory.Exists(FFolder.Text) then begin ShowMessage('Selecione uma pasta válida.'); Exit; end; FItems:=Preview(FFolder.Text,FPrefix.Text,FSuffix.Text,FFind.Text,FReplace.Text,FNumber.Checked); FGrid.RowCount:=Length(FItems)+1; for I:=0 to High(FItems) do begin FGrid.Cells[0,I+1]:=ExtractFileName(FItems[I].Source); FGrid.Cells[1,I+1]:=ExtractFileName(FItems[I].Target); FGrid.Cells[2,I+1]:=FItems[I].ErrorText; end; end;
procedure TMainWindow.Apply(Sender:TObject); begin if Length(FItems)=0 then begin ShowMessage('Gere a prévia primeiro.'); Exit; end; if MessageDlg('Confirma a renomeação dos itens sem conflito?',mtConfirmation,[mbYes,mbNo],0)=mrYes then begin Execute(FItems,LogPath); ShowMessage('Concluído. Use Desfazer para reverter a última operação.'); BuildPreview(nil); end; end;
procedure TMainWindow.Revert(Sender:TObject); begin try Undo(LogPath); ShowMessage('Operação desfeita.'); BuildPreview(nil); except on E:Exception do ShowMessage(E.Message); end; end;
end.
